#!/usr/bin/env python3
"""Emit WitnessData.v: Coq boolean order tables + nat key functions for the
repair-clock witnesses, from the validated harness. Each realizer is self-checked
with clock_is_exact before emission so the Coq data cannot drift from the z3 result.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from clock_realizer import pg_of, extract_realizer, reachable_closure, clock_of, clock_is_exact

WITNESSES = {
    "block":  (2, [(0, 1)]),
    "repair": (4, [(0, 1), (2, 3), (0, 3), (0, 2), (1, 3)]),
    "crown":  (4, [(0, 1), (2, 3), (0, 2), (1, 3)]),
}


def reach_le(n, syncs):
    nv, edges = pg_of(n, syncs)
    reach = reachable_closure(nv, edges)
    def le(x, y):
        return x == y or y in reach[x]
    return nv, le


def emit_bool_table(name, nv, le):
    lines = [f"Definition Rb_{name} (x y : Fin.t {nv}) : bool :="]
    lines.append(f"  match fin_to_nat x, fin_to_nat y with")
    for x in range(nv):
        for y in range(nv):
            if le(x, y):
                lines.append(f"  | {x}, {y} => true")
    lines.append("  | _, _ => false")
    lines.append("  end.")
    return "\n".join(lines)


def emit_keys(name, keys):
    out = []
    for ki, key in enumerate(keys, start=1):
        out.append(f"Definition k{ki}_{name} (x : Fin.t {len(key)}) : nat :=")
        out.append(f"  match fin_to_nat x with")
        for i, v in enumerate(key):
            out.append(f"  | {i} => {v}")
        out.append("  | _ => 0")
        out.append("  end.")
    return "\n".join(out)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(os.path.join(here, "..", "..", "..",
            "execution_clock", "witnesses", "WitnessData.v"))
    blocks = []
    blocks.append("(* GENERATED by nomadim/data/frontier-sync/emit_coq_witness.py — do not edit. *)")
    blocks.append("From Stdlib Require Import Fin Arith.")
    blocks.append("Definition fin_to_nat {n} (x : Fin.t n) : nat := proj1_sig (Fin.to_nat x).")
    for name in ("block", "repair", "crown"):
        n, syncs = WITNESSES[name]
        nv, le = reach_le(n, syncs)
        blocks.append(f"(* {name}: N={n} syncs={syncs} nv={nv} *)")
        blocks.append(emit_bool_table(name, nv, le))
        if name != "crown":
            rz = extract_realizer(*pg_of(n, syncs))
            assert rz is not None, f"{name} not dim<=2!"
            ok, bad = clock_is_exact(*pg_of(n, syncs), clock_of(*pg_of(n, syncs)))
            assert ok, f"{name} realizer not exact: {bad}"
            blocks.append(emit_keys(name, list(rz)))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n\n".join(blocks) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
