#!/usr/bin/env python3
"""Regenerate the table of contents in dimension-index.md.

Idempotent: rebuilds the block between the TOC markers from the section
headers (`## N. ...`) and entry headers (`#### [TYPE] id — Title`). If the
markers are absent, inserts a fresh `## Contents` block just before the first
numbered section. Run from anywhere:

    python3 docs/references/gen-toc.py

Used by the keep-the-TOC-updated hook (see .claude/settings.json).
"""
from __future__ import annotations

import pathlib
import re
import sys

INDEX = pathlib.Path(__file__).with_name("dimension-index.md")
START = "<!-- TOC START (auto-generated by gen-toc.py — do not edit) -->"
END = "<!-- TOC END -->"

SECTION_RE = re.compile(r"^## (\d+)\. (.+)$")
ENTRY_RE = re.compile(r"^#### \[([A-Z]+)\] ([a-z0-9-]+) — (.+)$")


def github_anchor(heading: str) -> str:
    """Approximate GitHub's heading-to-anchor slug."""
    slug = heading.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)  # drop punctuation (incl. . : ( ))
    slug = slug.replace(" ", "-")
    return slug


def build_toc(lines: list[str]) -> str:
    out: list[str] = []
    counts: dict[str, int] = {}
    total = 0
    for line in lines:
        m = SECTION_RE.match(line)
        if m:
            num, title = m.group(1), m.group(2)
            anchor = github_anchor(f"{num}. {title}")
            out.append(f"{num}. [{title}](#{anchor})")
            continue
        m = ENTRY_RE.match(line)
        if m:
            typ, eid, title = m.group(1), m.group(2), m.group(3)
            out.append(f"   - `[{typ}] {eid}` — {title}")
            counts[typ] = counts.get(typ, 0) + 1
            total += 1
    summary = ", ".join(f"{counts[t]} {t}" for t in
                        ["DEF", "FACT", "THM", "LEM", "ALG", "CONJ"] if t in counts)
    header = f"_{total} entries ({summary}). Auto-generated — do not edit between the markers._"
    return header + "\n\n" + "\n".join(out)


def main() -> int:
    text = INDEX.read_text(encoding="utf-8")
    lines = text.splitlines()
    toc_body = build_toc(lines)
    block = f"{START}\n{toc_body}\n{END}"

    if START in text and END in text:
        new = re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            lambda _m: block,
            text,
            count=1,
            flags=re.DOTALL,
        )
    else:
        # Insert a Contents section before the first numbered section header.
        out_lines: list[str] = []
        inserted = False
        for line in lines:
            if not inserted and SECTION_RE.match(line):
                out_lines.append("## Contents")
                out_lines.append("")
                out_lines.append(block)
                out_lines.append("")
                inserted = True
            out_lines.append(line)
        if not inserted:  # no sections yet — append at end
            out_lines += ["", "## Contents", "", block, ""]
        new = "\n".join(out_lines) + ("\n" if text.endswith("\n") else "")

    if new != text:
        INDEX.write_text(new, encoding="utf-8")
        print(f"gen-toc: updated {INDEX.name}")
    else:
        print(f"gen-toc: {INDEX.name} already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
