#!/usr/bin/env python3
"""Generate proprietary-papers.md: the closed-access sources behind the indexes.

Classifies every entry in sources.bib into:
  * local      — we hold a copy (note contains "Saved:")
  * open       — freely available but not stored (note mentions Open/arXiv)
  * proprietary — paywalled / book / JSTOR / publisher; needs manual access

For each proprietary source it lists the citation, venue, link, access tag, and
which knowledge-index entries cite it. Re-run after editing sources.bib or an
index:

    python3 docs/references/gen-proprietary.py
"""
from __future__ import annotations

import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
BIB = HERE / "sources.bib"
INDEXES = sorted(HERE.glob("*-index.md"))
OUT = HERE / "proprietary-papers.md"

FIELD = re.compile(r"(\w+)\s*=\s*\{(.*?)\}\s*,?\s*$", re.DOTALL)


def parse_bib(text: str) -> list[dict]:
    entries = []
    for m in re.finditer(r"@(\w+)\s*\{\s*([^,]+),(.*?)\n\}", text, re.DOTALL):
        etype, key, body = m.group(1), m.group(2).strip(), m.group(3) + "\n"
        fields = {"_type": etype, "_key": key}
        for fm in re.finditer(r"(\w+)\s*=\s*\{(.*?)\}\s*,?\s*\n", body, re.DOTALL):
            fields[fm.group(1).lower()] = re.sub(r"\s+", " ", fm.group(2)).strip()
        entries.append(fields)
    return entries


def delatex(s: str) -> str:
    """Strip common BibTeX/LaTeX accent escapes for readable display."""
    for pat, rep in [
        (r'\{\\"([a-zA-Z])\}', r"\1"), (r'\\"\{?([a-zA-Z])\}?', r"\1"),
        (r"\{\\'([a-zA-Z])\}", r"\1"), (r"\\'\{?([a-zA-Z])\}?", r"\1"),
        (r"\{\\v ?([a-zA-Z])\}", r"\1"), (r"\\v\{([a-zA-Z])\}", r"\1"),
        (r"\{\\H ([a-zA-Z])\}", r"\1"), (r"\\H\{([a-zA-Z])\}", r"\1"),
        (r"\{\\r ?([a-zA-Z])\}", r"\1"),
    ]:
        s = re.sub(pat, rep, s)
    return s.replace("{", "").replace("}", "")


def classify(note: str) -> str:
    if "Saved:" in note:
        return "local"
    if "Open" in note or "arXiv" in note:
        return "open"
    return "proprietary"


def citing_map() -> dict[str, list[str]]:
    """key -> sorted list of 'index:entry-id' that cite it."""
    cites: dict[str, set[str]] = {}
    for idx in INDEXES:
        label = idx.name.replace("-index.md", "")
        cur = None
        for line in idx.read_text(encoding="utf-8").splitlines():
            hm = re.match(r"^#### \[[A-Z]+\] ([a-z0-9-]+) ", line)
            if hm:
                cur = hm.group(1)
                continue
            if cur:
                for k in re.findall(r"\[([A-Za-z][A-Za-z0-9]+[0-9]{2,})\]", line):
                    cites.setdefault(k, set()).add(f"{label}:{cur}")
    return {k: sorted(v) for k, v in cites.items()}


def venue(e: dict) -> str:
    for f in ("journal", "booktitle", "publisher", "school"):
        if f in e:
            v = e[f]
            if f == "school":
                return f"{v} (thesis)"
            return v
    return ""


def access_tag(note: str) -> str:
    low = note.lower()
    if "jstor" in low:
        return "JSTOR"
    if "ams" in low:
        return "AMS / JSTOR"
    if "book" in low:
        return "Book"
    if "springer" in low:
        return "Springer"
    if "elsevier" in low:
        return "Elsevier"
    return "Publisher paywall"


def fmt(e: dict, cites: dict[str, list[str]]) -> str:
    key = e["_key"]
    auth = delatex(e.get("author", "")).replace(" and ", ", ")
    title = delatex(e.get("title", ""))
    v = delatex(venue(e))
    yr = e.get("year", "")
    loc = ", ".join(p for p in (e.get("volume", ""), e.get("pages", "")) if p)
    link = (f"https://doi.org/{e['doi']}" if "doi" in e else e.get("url", ""))
    tag = "Book" if e["_type"] == "book" else access_tag(e.get("note", ""))
    by = cites.get(key, [])
    head = f"- **[{key}]** {auth}. *{title}*."
    meta = f"  {v}" + (f" {loc}" if loc else "") + (f" ({yr})." if yr else ".")
    parts = [head, meta, f"  Access: {tag}." + (f" {link}" if link else "")]
    if by:
        parts.append(f"  Cited by: {', '.join('`' + b + '`' for b in by)}")
    return "\n".join(parts)


def main() -> int:
    entries = parse_bib(BIB.read_text(encoding="utf-8"))
    cites = citing_map()
    buckets: dict[str, list[dict]] = {"proprietary": [], "open": [], "local": []}
    for e in entries:
        buckets[classify(e.get("note", ""))].append(e)
    prop = sorted(buckets["proprietary"], key=lambda e: (e.get("year", ""), e["_key"]))
    books = [e for e in prop if e["_type"] == "book"]
    papers = [e for e in prop if e["_type"] != "book"]

    lines: list[str] = []
    lines.append("# Proprietary (closed-access) sources")
    lines.append("")
    lines.append(
        "Auto-generated by `gen-proprietary.py` from `sources.bib` — **do not edit by hand**. "
        "These are the references behind the knowledge indexes that are paywalled, book-only, "
        "or otherwise not freely downloadable; obtain them via institutional/library access. "
        f"({len(papers)} papers, {len(books)} books; "
        f"{len(buckets['local'])} other sources are stored locally and "
        f"{len(buckets['open'])} are open-access — see the appendix.)"
    )
    lines.append("")
    lines.append("## Closed-access papers")
    lines.append("")
    lines += [fmt(e, cites) for e in papers]
    lines.append("")
    lines.append("## Books")
    lines.append("")
    lines += [fmt(e, cites) for e in books]
    lines.append("")
    lines.append("## Appendix — open-access, not stored locally")
    lines.append("")
    lines.append(
        "Freely available (no paywall); not kept in the repo. Fetch from the link if needed."
    )
    lines.append("")
    for e in sorted(buckets["open"], key=lambda e: (e.get("year", ""), e["_key"])):
        link = (f"https://doi.org/{e['doi']}" if "doi" in e else e.get("url", ""))
        lines.append(f"- **[{e['_key']}]** {delatex(e.get('author','')).replace(' and ', ', ')}. "
                     f"*{delatex(e.get('title',''))}*. {delatex(venue(e))} ({e.get('year','')}). {link}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen-proprietary: wrote {OUT.name} "
          f"({len(papers)} papers, {len(books)} books, "
          f"{len(buckets['open'])} open, {len(buckets['local'])} local)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
